development:
  adapter: mysql2
  database: mobile_cms_development
  username: root
  password:
  host: localhost

test: &test
  adapter: mysql2
  database: mobile_cms_test
  username: root
  password:

cucumber:
  <<: *test
