development:
  adapter: mysql2
  database: mobile_cms_development
  username: root
  password:
  host: localhost

test: &test
  adapter: mysql2
  database: mobile_cms_test
  username: root
  password:

production:
  adapter: mysql2
  database: "<%=ENV['OPENSHIFT_APP_NAME']%>"
  username: "<%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>"
  password: "<%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>"
  host:     <%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_MYSQL_DB_PORT']%>

cucumber:
  <<: *test
